#!/bin/bash
# stanman cpplib documentation wrapper
# Author: Jack Rosenthal
# requires w3m (you can change this, update the var below)
# usage: stanman [PAGE_NAME]
browser='w3m -o confirm_qq=0'
docroot="$HOME/.lib/cpplib/doc"
command -v ${browser%% *} >/dev/null ||
    { echo "This script requires ${browser%% *}." ; exit 1; }

# Download the Stanford Library documentation if it isn't already
if [ ! -d "$docroot" ]; then
    mkdir -p $HOME/.lib
    wget -O$HOME/.lib/cpplib.zip http://eecs.mines.edu/Courses/csci262/resources/dist/cpplib.zip
    unzip -d $HOME/.lib -q -o $HOME/.lib/cpplib.zip
    rm $HOME/.lib/cpplib.zip
fi

case $# in
    0 )
        page=index.html
        ;;
    1 )
        page="$1-class.html"
        if ! [[ -e "$docroot/$page" ]]; then page="$1.html"; fi
        ;;
    * )
        echo "Usage: $0 [PAGE_NAME]" && exit
        ;;
esac

$browser "$docroot/$page"
